set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'pschmitt/tmux-forsaken'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g prefix C-a
bind C-a send-prefix
unbind C-b
set -g mouse on
set -g history-limit 50000
set -g focus-events on
set-window-option -g mode-keys vi

set-option -g @forsaken-kill-windows-ttr-key "v"
set-option -g @forsaken-kill-windows-ttr-confirm "Do you really want to kill all windows to the right of the current?"

set -g @ukiyo-plugins "time"
set -g @ukiyo-time-format "%F %R"
set -g @ukiyo-ignore-window-colors true
set -g @ukiyo-refresh-rate 60
set -g @continuum-restore 'on'

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g automatic-rename-format '#(~/.local/bin/tmux-window-name #{q:pane_current_path})'

set -g status-position top

run '~/.tmux/plugins/tpm/tpm'

set -g status-right "#(~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#{?#{<:%H,06},#[bg=red#,fg=#ffffff],#[fg=#dcd7ba#,bg=#54546D]} %F %R "
